version: '3.8'
services:
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports: 
            - "1433:1433"
        deploy:
            resources:
                reservations:
                    cpus: '2'
                    memory: 2GB
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        volumes:
            - sqldata:/var/opt/mssql/server

    web-app:
        container_name: web-app
        image: martin0219contactscr.azurecr.io/contacts
        domainname: MartinDogandzhiyski-contacts
        ports:
            - "80:80"
        restart: on-failure

volumes:
    sqldata:
        driver: azure_file
        driver_opts:
            share_name: sql-volume
            storage_account_name: martin0219contactssa